# Generated by Django 3.1.2 on 2022-01-06 08:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0002_auto_20220106_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('batch', models.CharField(default='N/A', max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('ordered_birds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('delivered_birds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('businessunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.businessunit', verbose_name='businessunit')),
                ('enterprisetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprisetype', verbose_name='enterprisetype')),
            ],
            options={
                'verbose_name_plural': 'DayOldChicks',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='CostCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Cost Categories',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField()),
                ('name', models.CharField(default='Not applicable', max_length=255)),
                ('phonenumber', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'layers_customers',
                'ordering': ['-reg_date'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vaccine', models.CharField(blank=True, max_length=10, null=True)),
                ('application_mode', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vaccination Program',
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_date', models.DateField()),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
                'ordering': ['-vendor_date'],
            },
        ),
        migrations.CreateModel(
            name='WeightTargets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_range', models.CharField(blank=True, max_length=10, null=True)),
                ('target_average_weight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Weight Targets',
            },
        ),
        migrations.CreateModel(
            name='WeightMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_date', models.DateField()),
                ('actual_maximum_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_manimum_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_average_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measuredby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.staff', verbose_name='measuredby')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.weighttargets', verbose_name='week')),
            ],
            options={
                'verbose_name_plural': 'Weight Monitoring',
                'ordering': ['-weight_date'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField()),
                ('vet_agrovet', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('implementedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.staff', verbose_name='implementedby')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.vaccinationprogram', verbose_name='vaccination')),
            ],
            options={
                'verbose_name_plural': 'Vaccination',
                'ordering': ['-vaccination_date'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(choices=[('', 'Product'), ('Eggs', 'Eggs'), ('Ex-layers', 'Ex-layers'), ('Manure', 'Manure')], default='', max_length=15)),
                ('payment_mode', models.CharField(choices=[('', 'Payment Mode'), ('Cash', 'Cash'), ('M-Pesa Till', 'M-Pesa Till'), ('Equitel', 'Equitel'), ('Bank', 'Bank'), ('Credit', 'Credit')], default='', max_length=15)),
                ('unit', models.CharField(choices=[('', 'UNIT'), ('Pieces', 'Pieces'), ('Crates', 'Crates'), ('Bags', 'Bags'), ('Kgs', 'Kgs')], default='', max_length=15)),
                ('quantity', models.IntegerField()),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.batch', verbose_name='batch')),
                ('businessunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.businessunit', verbose_name='businessunit')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.customers', verbose_name='customer')),
                ('enterprisetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprisetype', verbose_name='enterprisetype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.staff', verbose_name='staff')),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_date', models.DateField()),
                ('gross', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('defects', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('broken', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.batch', verbose_name='batch')),
                ('businessunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.businessunit', verbose_name='businessunit')),
                ('enterprisetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprisetype', verbose_name='enterprisetype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.staff', verbose_name='staff')),
            ],
            options={
                'verbose_name_plural': 'Production',
                'ordering': ['-prod_date'],
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('expense_details', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('', 'Payment Type'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('M-Pesa Till', 'M-Pesa Till'), ('Equitel', 'Equitel'), ('Credit', 'Credit')], default='', max_length=15)),
                ('businessunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.businessunit', verbose_name='businessunit')),
                ('cost_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.costcategories', verbose_name='cost category')),
                ('enterprisetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprisetype', verbose_name='enterprisetype')),
                ('paymentpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentfor', to='layers.batch', verbose_name='paymentpoint')),
                ('paymentsource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentfrom', to='layers.batch', verbose_name='paymentsource')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.staff', verbose_name='staff')),
                ('vendor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='layers.vendors', verbose_name='vendor')),
            ],
            options={
                'verbose_name_plural': 'Layers Expenses',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalment_date', models.DateField()),
                ('instalment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_mode', models.CharField(choices=[('', 'Payment Mode'), ('Cash', 'Cash'), ('M-Pesa Till', 'M-Pesa Till'), ('Equitel', 'Equitel'), ('Bank', 'Bank')], default='', max_length=15)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.staff', verbose_name='recipient')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.sales', verbose_name='creditsale')),
            ],
            options={
                'verbose_name_plural': 'Credit Sales',
                'ordering': ['-instalment_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalment_date', models.DateField()),
                ('instalment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_mode', models.CharField(choices=[('', 'Payment Mode'), ('Cash', 'Cash'), ('M-Pesa Till', 'M-Pesa Till'), ('Equitel', 'Equitel'), ('Bank', 'Bank')], default='', max_length=15)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.expenses', verbose_name='creditexpense')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.staff', verbose_name='recipient')),
            ],
            options={
                'verbose_name_plural': 'Credit Expenses',
                'ordering': ['-instalment_date'],
            },
        ),
        migrations.CreateModel(
            name='BirdsStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('stock_movement_type', models.CharField(choices=[('', 'Type of Movement'), ('Stock Taking', 'Stock Taking'), ('Stock In', 'Stock In'), ('Stock Out', 'Stock Out')], default='', max_length=15)),
                ('stock_movement_reason', models.CharField(choices=[('', 'Reason'), ('Day Old Chicks', 'Day Old Chicks'), ('Stock Taking', 'Stock Taking'), ('Mortality', 'Mortality'), ('Stolen', 'Stolen'), ('Unaccounted', 'Unaccounted'), ('Error Correction', 'Error Correction'), ('Others', 'Others')], default='', max_length=16)),
                ('birds', models.IntegerField(default=0)),
                ('birds_stock_actual', models.IntegerField(blank=True)),
                ('stock_movement_notes', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.batch', verbose_name='batch')),
                ('businessunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.businessunit', verbose_name='businessunit')),
                ('enterprisetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprisetype', verbose_name='enterprisetype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.staff', verbose_name='staff')),
            ],
            options={
                'verbose_name_plural': 'Birds Stock',
                'ordering': ['-stock_date'],
            },
        ),
    ]
