# Generated by Django 3.1.2 on 2022-01-06 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_auto_20220106_1137'),
        ('layers', '0002_auto_20220106_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-purchase_date'], 'verbose_name_plural': 'Expenses'},
        ),
        migrations.RenameField(
            model_name='weightmonitoring',
            old_name='actual_manimum_weight',
            new_name='actual_minimum_weight',
        ),
        migrations.RemoveField(
            model_name='creditexpenses',
            name='recipient',
        ),
        migrations.AddField(
            model_name='creditexpenses',
            name='paymentby',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='enterprises.staff', verbose_name='paymentby'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='batch',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='layers.batch', verbose_name='batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weightmonitoring',
            name='batch',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='layers.batch', verbose_name='batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sales',
            name='unit',
            field=models.CharField(choices=[('', 'Unit'), ('Pieces', 'Pieces'), ('Crates', 'Crates'), ('Bags', 'Bags'), ('Kgs', 'Kgs')], default='', max_length=15),
        ),
    ]
