# Generated by Django 3.1.2 on 2022-01-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_auto_20220106_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='createdBy',
        ),
    ]
