# Generated by Django 3.1.2 on 2022-01-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_banking_paymentmodes'),
        ('layers', '0005_remove_batch_createdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_movement_type', models.CharField(max_length=255)),
                ('stock_movement_category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Stock Movement Types',
            },
        ),
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateField()),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.banking', verbose_name='bank')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.batch', verbose_name='batch')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.staff', verbose_name='staff')),
            ],
            options={
                'verbose_name_plural': 'Cash Deposit',
                'ordering': ['-deposit_date'],
            },
        ),
    ]
