# Generated by Django 3.1.2 on 2022-01-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0007_auto_20220115_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdsstock',
            name='stock_movement_reason',
        ),
        migrations.AlterField(
            model_name='birdsstock',
            name='stock_movement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.stockmovement', verbose_name='stock_movement_type'),
        ),
    ]
