# Generated by Django 3.1.2 on 2022-01-16 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_banking_paymentmodes'),
        ('layers', '0008_auto_20220115_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(blank=True, max_length=30, null=True)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Feed Types',
            },
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='paymentpoint',
            new_name='batch',
        ),
        migrations.RemoveField(
            model_name='eggsinventory',
            name='businessunit',
        ),
        migrations.RemoveField(
            model_name='eggsinventory',
            name='enterprisetype',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='businessunit',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='enterprisetype',
        ),
        migrations.RemoveField(
            model_name='production',
            name='businessunit',
        ),
        migrations.RemoveField(
            model_name='production',
            name='enterprisetype',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='businessunit',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='enterprisetype',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='unit',
        ),
        migrations.AddField(
            model_name='costcategories',
            name='cost_sub_category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='birdsstock',
            name='birds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='birdsstock',
            name='birds_stock_actual',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='creditexpenses',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.paymentmodes', verbose_name='payment_mode'),
        ),
        migrations.AlterField(
            model_name='creditsales',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.paymentmodes', verbose_name='payment_mode'),
        ),
        migrations.AlterField(
            model_name='eggsinventory',
            name='egg_loss_breakages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eggsinventory',
            name='egg_loss_defects',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eggsinventory',
            name='egg_loss_unaccounted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eggsinventory',
            name='eggs_stock_actual_crates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eggsinventory',
            name='eggs_stock_actual_pieces',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.paymentmodes', verbose_name='payment_mode'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.paymentmodes', verbose_name='payment_mode'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.products', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='vaccinationprogram',
            name='vaccine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FeedInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('stock_in', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('stock_out', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('bags_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.batch', verbose_name='batch')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.feedtypes', verbose_name='feed_type')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.staff', verbose_name='staff')),
            ],
            options={
                'verbose_name_plural': 'Feeds Inventory',
            },
        ),
    ]
