# Generated by Django 3.1.2 on 2022-01-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0009_auto_20220116_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdsstock',
            name='birds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='birdsstock',
            name='birds_stock_actual',
            field=models.IntegerField(default=0),
        ),
    ]
