# Generated by Django 4.0 on 2022-03-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0012_rename_active_batch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='birds',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='layers.birdsstock', verbose_name='birds'),
        ),
    ]
