# Generated by Django 3.1.2 on 2022-03-19 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0014_auto_20220319_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='birds',
        ),
    ]
