# Generated by Django 4.0 on 2022-05-07 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0016_production_birds_alter_batch_id_alter_birdsstock_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='birds',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
