# Generated by Django 4.0 on 2022-06-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0018_rename_name_customers_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, default='notapplicable@gmail.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='location',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phonenumber',
            field=models.CharField(blank=True, default='N/A', max_length=10, null=True),
        ),
    ]
