# Generated by Django 4.0 on 2022-06-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0020_rename_product_products_productname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ['reg_date'], 'verbose_name_plural': 'Customers'},
        ),
    ]
