# Generated by Django 4.0 on 2022-08-05 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0023_rename_bank_cashbalance_banking'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsinventory',
            name='egg_loss_transport',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eggsinventory',
            name='eggs_stock_actual_crates',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='eggsinventory',
            name='eggs_stock_actual_pieces',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
