# Generated by Django 4.0 on 2022-08-10 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0024_eggsinventory_egg_loss_transport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='layers.feedtypes', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='feedtypes',
            name='package',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedtypes',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
