# Generated by Django 4.0 on 2022-08-10 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0025_expenses_unit_feedtypes_package_feedtypes_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedtypes',
            name='feed_type',
        ),
        migrations.AddField(
            model_name='feedtypes',
            name='feed_type_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.costcategories', verbose_name='feed_type'),
        ),
    ]
