# Generated by Django 4.0 on 2022-08-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0026_remove_feedtypes_feed_type_feedtypes_feed_type_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedinventory',
            name='stock_out',
        ),
    ]
