# Generated by Django 4.0 on 2022-08-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0027_remove_feedinventory_stock_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedtypes',
            old_name='package',
            new_name='unitmeasure',
        ),
    ]
