# Generated by Django 4.0 on 2022-08-10 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0029_alter_expenses_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='layers.feedtypes', verbose_name='unit'),
        ),
    ]
