# Generated by Django 4.0 on 2022-08-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0035_alter_expenses_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedinventory',
            name='feed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.expenses', verbose_name='feed_type'),
        ),
    ]
