# Generated by Django 4.0 on 2022-08-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0036_alter_feedinventory_feed_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightmonitoring',
            options={'ordering': ['weight_date'], 'verbose_name_plural': 'Weight Monitoring'},
        ),
    ]
