# Generated by Django 4.0 on 2022-08-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0037_alter_weightmonitoring_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationprogram',
            name='week',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
