# Generated by Django 4.0 on 2022-08-15 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0038_alter_vaccinationprogram_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationprogram',
            name='vaccination_day',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
