# Generated by Django 4.0 on 2022-08-18 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0039_vaccinationprogram_vaccination_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccination',
            options={'ordering': ['vaccination_date'], 'verbose_name_plural': 'Vaccination'},
        ),
        migrations.AddField(
            model_name='vaccinationprogram',
            name='vaccine_regimen',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
