# Generated by Django 4.0 on 2022-08-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0043_alter_feedtargets_feed_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedinventory',
            options={'ordering': ['stock_date'], 'verbose_name_plural': 'Feeds Inventory'},
        ),
        migrations.AddField(
            model_name='feedinventory',
            name='bags_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
