# Generated by Django 4.0 on 2022-09-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0044_alter_feedinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['prod_date'], 'verbose_name_plural': 'Production'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['date'], 'verbose_name_plural': 'Sales'},
        ),
    ]
