# Generated by Django 4.0 on 2022-09-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0045_alter_production_options_alter_sales_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['delivery_date'], 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='birdsstock',
            options={'ordering': ['batch'], 'verbose_name_plural': 'Birds Stock'},
        ),
        migrations.AlterModelOptions(
            name='cashbalance',
            options={'ordering': ['deposit_date'], 'verbose_name_plural': 'Cash Deposit'},
        ),
        migrations.AlterModelOptions(
            name='creditexpenses',
            options={'ordering': ['instalment_date'], 'verbose_name_plural': 'Credit Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['purchase_date'], 'verbose_name_plural': 'Expenses'},
        ),
    ]
