# Generated by Django 4.0 on 2021-12-30 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Business Unit',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Enterprise Type',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('businessunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.businessunit')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.AddField(
            model_name='businessunit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.company'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='enterprisetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.enterprisetype'),
        ),
    ]
