# Generated by Django 4.0 on 2022-09-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0007_rename_bank_name_banking_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodes',
            name='type',
        ),
    ]
